### PR TITLE
add GemStone baseline info.  Loading PackageManifest stub class

### PR DESCRIPTION
**Pull request by pdebruic**

### CODE REVIEW

**Comment by jecisc** [comment]
Relative issue: https://github.com/DuneSt/MaterialColors/issues/5

**Comment by jecisc** [comment]
Since it's a small project I think it would be easy to enable Gemstone for the builds.

Can you tell me what is the current Gemstone version we should test with? GemStone-3.3.x?

**Comment by jecisc** [comment]
I see that Metacello test GemStone-3.3.6.

**Comment by pdebruic** [comment]
3.4.1

**Comment by pdebruic** [comment]
3.4.1 is the latest stable released version.  They recommend it for new projects


They just released a bug fix 3.3.7 a couple days ago

**Comment by jecisc** [comment]
great thank you!

**Comment by jecisc** [comment]
@pdebruic Thank you!

**Pull request merged**
