### PR TITLE
Enable Gemstone in the CI

### PR DESCRIPTION
**Pull request by jecisc**
Fixes https://github.com/DuneSt/MaterialColors/issues/6

### CODE REVIEW

**Comment by jecisc** [comment]
@pdebruic I'll not be able to release the gemstone release of MaterialColor now since there is 1 failure and 4 errors in the 5 tests currently in the project :(

**Comment by jecisc** [comment]
Part of the problem comes from this issue: https://github.com/DuneSt/MaterialColors/issues/10

**Comment by jecisc** [comment]
#allMethods does not exits in Gemstone :(

**Comment by jecisc** [comment]
@pdebruic Sorry to bother you again but do you know if there is a way for me to browser Gemstone code?

I do not use Gemstone and also I'm on Windows :( It's hard to correct Gemstones issues without been able to see what methods Gemstone implements.

**Comment by jecisc** [comment]
This is weird. 

I get this error: ` MessageNotUnderstood occurred (error 2010), a MaterialColorPlatform class does not understand  #'current'`

But I see the method in the code...

https://github.com/DuneSt/MaterialColors/pull/9/files#diff-163b5fcdde3352da3d88e9f83dc37092R2

**Comment by jecisc** [comment]
I really have no idea of the source of `MessageNotUnderstood occurred (error 2010), a MaterialColorPlatform class does not understand #'current'`... :(

**Comment by jecisc** [comment]
@pdebruic Sorry to bother you again but do you know a way to get a class name as a string?

When sending #name I get the class name but with an "a/an" in front. 

(I wanted to check myself but gemstone installation of Windows linux subsystem failed. Same for my Fedora virtual machine and same for my ubuntu 18.04 virtual machine. Each time for a different reason :( )

**Comment by pdebruic** [comment]
No problem.  


1 class name


gives #'SmallInteger'




Also in GemStone symbols ~= strings.  So #'Integer' ~= 'Integer' etc etc etc.  I think you know that from some baseline fixes a while ago but wanted to be sure.  


I don't know that they're supporting anything but the Ubuntu LTS releases and the CentOS/Redhat releases for installation.  Strange that it wouldn't load on Fedora or Ubuntu 18.04 


You could ask on their mailing list: http://forum.world.st/GLASS-f1460844.html

**Comment by jecisc** [comment]
From the test failure in travis logs I have the impression that `MDLColor Orange class name` returns "aMDLColor".

**Comment by pdebruic** [comment]
MDLColor orange class name


gives 	the symbol #'MDLColor'


MDLColor orange class


gives the class MDLColor

**Comment by pdebruic** [comment]
oh.  missed the name on the end there of code example in your email.  Sorry

**Comment by pdebruic** [comment]
MDLColor yellow asString

returns 

'anMDLColor'


which is the print string for the class.  


Object>>#asString is

asString
  "Returns a String that indicates the class of the receiver; for
 example, if the receiver is an instance of class Monkey, it returns
 a String of the form 'aMonkey'.  This method is often
 overridden in subclasses to provide behavior tailored to the class.

 The result should not contain any formatting information.  
 For example the following expression should evaluate to true:

   #abc asString = String withAll: 'abc'

 This method is used by Object | describe.  Thus GemStone error
 handling and Topaz are dependent upon this method being functional.

 Must conform to rules for reimplementation of Object | describe."

  ^ self class name describeClassName





So its not using the #printOn: method like you expect

**Comment by jecisc** [comment]
Thank you,

I found the problem, it was between the keyboard and the screen! I was looking at #storeOn: and I don't know why I mixed #storeOn: and #asString in my head. 

Later I'll correct that and it should be good to merge.

**Comment by jecisc** [comment]
Ok, I know where is the problem! 

In Pharo Color>>printOn: calls #storeOn:

**Comment by pdebruic** [comment]
Well yea in GemStone the Color>>#printOn: method is different than Pharo's 

Pharo:

printOn: aStream
	| name |
	(name := self name).
	name = #unnamed
		ifFalse: [ 
			^ aStream
				nextPutAll: 'Color ';
				nextPutAll: name ].
	self storeOn: aStream



GemStone

printOn: aStream
  | name |
  (name _ self name)
    ifNotNil: [ 
      ^ aStream
        nextPutAll: 'Color ';
        nextPutAll: name ].
  self storeOn: aStream


So its the explicit hardcoding of #unnamed in MDLColor>>#name that makes things wonky

**Comment by jecisc** [comment]
Maybe I can just change MDLColor>>name to this:


```Smalltalk
MaterialColorPlatform current unamedColorName
```

For Pharo it can returns `#unamed` and for Gemstone `nil`

**Comment by pdebruic** [comment]
Why not give MDLColor a printOn: method as you're bypassing the name printing of Pharo's anyway so never intend for the name to be printed?

**Pull request merged**
